images:
  frappe:
    repository: yassmin970/frappe
    tag: latest

mariadb:
  enabled: true
  rootUser:
    password: root_password

redis:
  enabled: true

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 8Gi

frappe:
  replicas: 1
  sites:
    - name: site1.local
      dbRootPassword: root
      adminPassword: admin
      installApps: erpnext

